In [1]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
customers = pd.read_csv('/content/drive/MyDrive/udmy/dataAnalisys/Archivos/ABC - Customers.csv')
sales = pd.read_csv('/content/drive/MyDrive/udmy/dataAnalisys/Archivos/ABC - Sales.csv')

Mounted at /content/drive

In [2]:
customers

    cust_id              customer
0         2        Anthony Creech
1         3       Veronika Napier
2         4            Femi Bello
3         5    Michelle Rushworth
4         6          Alie Sandeep
5         7        Gaylor Jennins
6         8          Kaia Raisher
7         9          Alano Kemery
8        10        Rozalie Roddie
9        11  Roderigo Staresmeare
10       12      Gabriele Painter
11       13       Joycelin Karlik
12       14     Celestia Gormally
13       15      Joline Bodsworth
14       16                Sue Li
15       17      Gallard Brassill
16       18  Melody Baltrushaitis
17       19     Brockie MacTeague
18       20     Fanchette Sinclar
19       21         Welsh Levinge
20       22            Puff Marsh
21       23         Zane Tregunna
22       24       Janka Taylorson
23       25           Mame Caddan
24       26            Page Coram
25       27       Tafadzwa Warden
26       28        Darcee Byfford
27       29         Roxane Lovell
28       30    Jacquette De Maine
29       31        Claribel Lomen

In [3]:
sales

    sale_id  cust_id  prod_id     product  qty     store_location
0       101       30        5      Heater    2      Fairview Mall
1       102       20       14       Piano    2            Rotunda
2       103       20       17   Microwave    1  Kessington Market
3       104        5        3     Speaker    3      Fairview Mall
4       105       10        4  Humidifier    1           Shoppers
5       106       14        4  Humidifier    1           Shoppers
6       107       28        2     Printer    3  Kessington Market
7       108       27       14       Piano    2        Brisby Mall
8       109        4        5      Heater    2        Brisby Mall
9       110        8        3     Speaker    3           Shoppers
10      111       30        4  Humidifier    2           Shoppers
11      112        8       13  Microphone    2  Kessington Market
12      113       13        5      Heater    2           Shoppers
13      114       30       15      Tripod    2            Rotunda
14      115       20       13  Microphone    2  Kessington Market
15      116        2        3     Speaker    2        Brisby Mall
16      117       10        3     Speaker    3  Kessington Market
17      118        8       17   Microwave    3           Shoppers
18      119        5        5      Heater    2            Rotunda
19      120       28        1   Headphone    1        Brisby Mall
20      121        4        5      Heater    3           Shoppers
21      122       24       16       Mixer    2        Brisby Mall
22      123       10        1   Headphone    2  Kessington Market
23      124       13       15      Tripod    1        Brisby Mall
24      125       27       17   Microwave    3           Shoppers
25      126        7        2     Printer    2  Kessington Market
26      127       24       14       Piano    1  Kessington Market
27      128       15       13  Microphone    1            Rotunda
28      129       14       19       Dryer    1        Brisby Mall
29      130       13       18      Washer    2           Shoppers

In [4]:
cust_sales = pd.merge(customers, sales, how = 'inner', on = 'cust_id')
cust_sales

,cust_id,customer,sale_id,prod_id,product,qty,store_location
0,2,Anthony Creech,116,3,Speaker,2,Brisby Mall
1,4,Femi Bello,109,5,Heater,2,Brisby Mall
2,4,Femi Bello,121,5,Heater,3,Shoppers
3,5,Michelle Rushworth,104,3,Speaker,3,Fairview Mall
4,5,Michelle Rushworth,119,5,Heater,2,Rotunda
5,7,Gaylor Jennins,126,2,Printer,2,Kessington Market
6,8,Kaia Raisher,110,3,Speaker,3,Shoppers
7,8,Kaia Raisher,112,13,Microphone,2,Kessington Market
8,8,Kaia Raisher,118,17,Microwave,3,Shoppers
9,10,Rozalie Roddie,105,4,Humidifier,1,Shoppers
10,10,Rozalie Roddie,117,3,Speaker,3,Kessington Market
11,10,Rozalie Roddie,123,1,Headphone,2,Kessington Market
12,13,Joycelin Karlik,113,5,Heater,2,Shoppers
13,13,Joycelin Karlik,124,15,Tripod,1,Brisby Mall
14,13,Joycelin Karlik,130,18,Washer,2,Shoppers
15,14,Celestia Gormally,106,4,Humidifier,1,Shoppers
16,14,Celestia Gormally,129,19,Dryer,1,Brisby Mall
17,15,Joline Bodsworth,128,13,Microphone,1,Rotunda
18,20,Fanchette Sinclar,102,14,Piano,2,Rotunda
19,20,Fanchette Sinclar,103,17,Microwave,1,Kessington Market
20,20,Fanchette Sinclar,115,13,Microphone,2,Kessington Market
21,24,Janka Taylorson,122,16,Mixer,2,Brisby Mall
22,24,Janka Taylorson,127,14,Piano,1,Kessington Market
23,27,Tafadzwa Warden,108,14,Piano,2,Brisby Mall
24,27,Tafadzwa Warden,125,17,Microwave,3,Shoppers
25,28,Darcee Byfford,107,2,Printer,3,Kessington Market
26,28,Darcee Byfford,120,1,Headphone,1,Brisby Mall
27,30,Jacquette De Maine,101,5,Heater,2,Fairview Mall
28,30,Jacquette De Maine,111,4,Humidifier,2,Shoppers
29,30,Jacquette De Maine,114,15,Tripod,2,Rotunda

In [5]:
#inner join
cust_sales = pd.merge(customers, sales[['cust_id', 'product', 'qty', 'store_location']], how = 'inner', on = 'cust_id')
cust_sales

    cust_id            customer     product  qty     store_location
0         2      Anthony Creech     Speaker    2        Brisby Mall
1         4          Femi Bello      Heater    2        Brisby Mall
2         4          Femi Bello      Heater    3           Shoppers
3         5  Michelle Rushworth     Speaker    3      Fairview Mall
4         5  Michelle Rushworth      Heater    2            Rotunda
5         7      Gaylor Jennins     Printer    2  Kessington Market
6         8        Kaia Raisher     Speaker    3           Shoppers
7         8        Kaia Raisher  Microphone    2  Kessington Market
8         8        Kaia Raisher   Microwave    3           Shoppers
9        10      Rozalie Roddie  Humidifier    1           Shoppers
10       10      Rozalie Roddie     Speaker    3  Kessington Market
11       10      Rozalie Roddie   Headphone    2  Kessington Market
12       13     Joycelin Karlik      Heater    2           Shoppers
13       13     Joycelin Karlik      Tripod    1        Brisby Mall
14       13     Joycelin Karlik      Washer    2           Shoppers
15       14   Celestia Gormally  Humidifier    1           Shoppers
16       14   Celestia Gormally       Dryer    1        Brisby Mall
17       15    Joline Bodsworth  Microphone    1            Rotunda
18       20   Fanchette Sinclar       Piano    2            Rotunda
19       20   Fanchette Sinclar   Microwave    1  Kessington Market
20       20   Fanchette Sinclar  Microphone    2  Kessington Market
21       24     Janka Taylorson       Mixer    2        Brisby Mall
22       24     Janka Taylorson       Piano    1  Kessington Market
23       27     Tafadzwa Warden       Piano    2        Brisby Mall
24       27     Tafadzwa Warden   Microwave    3           Shoppers
25       28      Darcee Byfford     Printer    3  Kessington Market
26       28      Darcee Byfford   Headphone    1        Brisby Mall
27       30  Jacquette De Maine      Heater    2      Fairview Mall
28       30  Jacquette De Maine  Humidifier    2           Shoppers
29       30  Jacquette De Maine      Tripod    2            Rotunda

In [6]:
#left join

In [7]:
customers['cust_id'].nunique()

30

In [8]:
sales['cust_id'].nunique()

14

In [9]:
df1 = pd.merge(customers, sales, how = 'left', on = 'cust_id')
df1

,cust_id,customer,sale_id,prod_id,product,qty,store_location
0,2,Anthony Creech,116.0,3.0,Speaker,2.0,Brisby Mall
1,3,Veronika Napier,NaN,NaN,NaN,NaN,NaN
2,4,Femi Bello,109.0,5.0,Heater,2.0,Brisby Mall
3,4,Femi Bello,121.0,5.0,Heater,3.0,Shoppers
4,5,Michelle Rushworth,104.0,3.0,Speaker,3.0,Fairview Mall
5,5,Michelle Rushworth,119.0,5.0,Heater,2.0,Rotunda
6,6,Alie Sandeep,NaN,NaN,NaN,NaN,NaN
7,7,Gaylor Jennins,126.0,2.0,Printer,2.0,Kessington Market
8,8,Kaia Raisher,110.0,3.0,Speaker,3.0,Shoppers
9,8,Kaia Raisher,112.0,13.0,Microphone,2.0,Kessington Market
10,8,Kaia Raisher,118.0,17.0,Microwave,3.0,Shoppers
11,9,Alano Kemery,NaN,NaN,NaN,NaN,NaN
12,10,Rozalie Roddie,105.0,4.0,Humidifier,1.0,Shoppers
13,10,Rozalie Roddie,117.0,3.0,Speaker,3.0,Kessington Market
14,10,Rozalie Roddie,123.0,1.0,Headphone,2.0,Kessington Market
15,11,Roderigo Staresmeare,NaN,NaN,NaN,NaN,NaN
16,12,Gabriele Painter,NaN,NaN,NaN,NaN,NaN
17,13,Joycelin Karlik,113.0,5.0,Heater,2.0,Shoppers
18,13,Joycelin Karlik,124.0,15.0,Tripod,1.0,Brisby Mall
19,13,Joycelin Karlik,130.0,18.0,Washer,2.0,Shoppers
20,14,Celestia Gormally,106.0,4.0,Humidifier,1.0,Shoppers
21,14,Celestia Gormally,129.0,19.0,Dryer,1.0,Brisby Mall
22,15,Joline Bodsworth,128.0,13.0,Microphone,1.0,Rotunda
23,16,Sue Li,NaN,NaN,NaN,NaN,NaN
24,17,Gallard Brassill,NaN,NaN,NaN,NaN,NaN
25,18,Melody Baltrushaitis,NaN,NaN,NaN,NaN,NaN
26,19,Brockie MacTeague,NaN,NaN,NaN,NaN,NaN
27,20,Fanchette Sinclar,102.0,14.0,Piano,2.0,Rotunda
28,20,Fanchette Sinclar,103.0,17.0,Microwave,1.0,Kessington Market
29,20,Fanchette Sinclar,115.0,13.0,Microphone,2.0,Kessington Market
30,21,Welsh Levinge,NaN,NaN,NaN,NaN,NaN
31,22,Puff Marsh,NaN,NaN,NaN,NaN,NaN
32,23,Zane Tregunna,NaN,NaN,NaN,NaN,NaN
33,24,Janka Taylorson,122.0,16.0,Mixer,2.0,Brisby Mall
34,24,Janka Taylorson,127.0,14.0,Piano,1.0,Kessington Market
35,25,Mame Caddan,NaN,NaN,NaN,NaN,NaN
36,26,Page Coram,NaN,NaN,NaN,NaN,NaN
37,27,Tafadzwa Warden,108.0,14.0,Piano,2.0,Brisby Mall
38,27,Tafadzwa Warden,125.0,17.0,Microwave,3.0,Shoppers
39,28,Darcee Byfford,107.0,2.0,Printer,3.0,Kessington Market
40,28,Darcee Byfford,120.0,1.0,Headphone,1.0,Brisby Mall
41,29,Roxane Lovell,NaN,NaN,NaN,NaN,NaN
42,30,Jacquette De Maine,101.0,5.0,Heater,2.0,Fairview Mall
43,30,Jacquette De Maine,111.0,4.0,Humidifier,2.0,Shoppers
44,30,Jacquette De Maine,114.0,15.0,Tripod,2.0,Rotunda
45,31,Claribel Lomen,NaN,NaN,NaN,NaN,NaN

In [10]:
#df1['sale_id']
df1['sale_id'].isnull()
df1[df1['sale_id'].isnull()]['customer']

1          Veronika Napier
6             Alie Sandeep
11            Alano Kemery
15    Roderigo Staresmeare
16        Gabriele Painter
23                  Sue Li
24        Gallard Brassill
25    Melody Baltrushaitis
26       Brockie MacTeague
30           Welsh Levinge
31              Puff Marsh
32           Zane Tregunna
35             Mame Caddan
36              Page Coram
41           Roxane Lovell
45          Claribel Lomen
Name: customer, dtype: object

In [11]:
pd.merge(customers, sales, how = "right", on = 'cust_id')

,cust_id,customer,sale_id,prod_id,product,qty,store_location
0,30,Jacquette De Maine,101,5,Heater,2,Fairview Mall
1,20,Fanchette Sinclar,102,14,Piano,2,Rotunda
2,20,Fanchette Sinclar,103,17,Microwave,1,Kessington Market
3,5,Michelle Rushworth,104,3,Speaker,3,Fairview Mall
4,10,Rozalie Roddie,105,4,Humidifier,1,Shoppers
5,14,Celestia Gormally,106,4,Humidifier,1,Shoppers
6,28,Darcee Byfford,107,2,Printer,3,Kessington Market
7,27,Tafadzwa Warden,108,14,Piano,2,Brisby Mall
8,4,Femi Bello,109,5,Heater,2,Brisby Mall
9,8,Kaia Raisher,110,3,Speaker,3,Shoppers
10,30,Jacquette De Maine,111,4,Humidifier,2,Shoppers
11,8,Kaia Raisher,112,13,Microphone,2,Kessington Market
12,13,Joycelin Karlik,113,5,Heater,2,Shoppers
13,30,Jacquette De Maine,114,15,Tripod,2,Rotunda
14,20,Fanchette Sinclar,115,13,Microphone,2,Kessington Market
15,2,Anthony Creech,116,3,Speaker,2,Brisby Mall
16,10,Rozalie Roddie,117,3,Speaker,3,Kessington Market
17,8,Kaia Raisher,118,17,Microwave,3,Shoppers
18,5,Michelle Rushworth,119,5,Heater,2,Rotunda
19,28,Darcee Byfford,120,1,Headphone,1,Brisby Mall
20,4,Femi Bello,121,5,Heater,3,Shoppers
21,24,Janka Taylorson,122,16,Mixer,2,Brisby Mall
22,10,Rozalie Roddie,123,1,Headphone,2,Kessington Market
23,13,Joycelin Karlik,124,15,Tripod,1,Brisby Mall
24,27,Tafadzwa Warden,125,17,Microwave,3,Shoppers
25,7,Gaylor Jennins,126,2,Printer,2,Kessington Market
26,24,Janka Taylorson,127,14,Piano,1,Kessington Market
27,15,Joline Bodsworth,128,13,Microphone,1,Rotunda
28,14,Celestia Gormally,129,19,Dryer,1,Brisby Mall
29,13,Joycelin Karlik,130,18,Washer,2,Shoppers

In [12]:
pd.merge(customers, sales, how = "outer", on = 'cust_id')

,cust_id,customer,sale_id,prod_id,product,qty,store_location
0,2,Anthony Creech,116.0,3.0,Speaker,2.0,Brisby Mall
1,3,Veronika Napier,NaN,NaN,NaN,NaN,NaN
2,4,Femi Bello,109.0,5.0,Heater,2.0,Brisby Mall
3,4,Femi Bello,121.0,5.0,Heater,3.0,Shoppers
4,5,Michelle Rushworth,104.0,3.0,Speaker,3.0,Fairview Mall
5,5,Michelle Rushworth,119.0,5.0,Heater,2.0,Rotunda
6,6,Alie Sandeep,NaN,NaN,NaN,NaN,NaN
7,7,Gaylor Jennins,126.0,2.0,Printer,2.0,Kessington Market
8,8,Kaia Raisher,110.0,3.0,Speaker,3.0,Shoppers
9,8,Kaia Raisher,112.0,13.0,Microphone,2.0,Kessington Market
10,8,Kaia Raisher,118.0,17.0,Microwave,3.0,Shoppers
11,9,Alano Kemery,NaN,NaN,NaN,NaN,NaN
12,10,Rozalie Roddie,105.0,4.0,Humidifier,1.0,Shoppers
13,10,Rozalie Roddie,117.0,3.0,Speaker,3.0,Kessington Market
14,10,Rozalie Roddie,123.0,1.0,Headphone,2.0,Kessington Market
15,11,Roderigo Staresmeare,NaN,NaN,NaN,NaN,NaN
16,12,Gabriele Painter,NaN,NaN,NaN,NaN,NaN
17,13,Joycelin Karlik,113.0,5.0,Heater,2.0,Shoppers
18,13,Joycelin Karlik,124.0,15.0,Tripod,1.0,Brisby Mall
19,13,Joycelin Karlik,130.0,18.0,Washer,2.0,Shoppers
20,14,Celestia Gormally,106.0,4.0,Humidifier,1.0,Shoppers
21,14,Celestia Gormally,129.0,19.0,Dryer,1.0,Brisby Mall
22,15,Joline Bodsworth,128.0,13.0,Microphone,1.0,Rotunda
23,16,Sue Li,NaN,NaN,NaN,NaN,NaN
24,17,Gallard Brassill,NaN,NaN,NaN,NaN,NaN
25,18,Melody Baltrushaitis,NaN,NaN,NaN,NaN,NaN
26,19,Brockie MacTeague,NaN,NaN,NaN,NaN,NaN
27,20,Fanchette Sinclar,102.0,14.0,Piano,2.0,Rotunda
28,20,Fanchette Sinclar,103.0,17.0,Microwave,1.0,Kessington Market
29,20,Fanchette Sinclar,115.0,13.0,Microphone,2.0,Kessington Market
30,21,Welsh Levinge,NaN,NaN,NaN,NaN,NaN
31,22,Puff Marsh,NaN,NaN,NaN,NaN,NaN
32,23,Zane Tregunna,NaN,NaN,NaN,NaN,NaN
33,24,Janka Taylorson,122.0,16.0,Mixer,2.0,Brisby Mall
34,24,Janka Taylorson,127.0,14.0,Piano,1.0,Kessington Market
35,25,Mame Caddan,NaN,NaN,NaN,NaN,NaN
36,26,Page Coram,NaN,NaN,NaN,NaN,NaN
37,27,Tafadzwa Warden,108.0,14.0,Piano,2.0,Brisby Mall
38,27,Tafadzwa Warden,125.0,17.0,Microwave,3.0,Shoppers
39,28,Darcee Byfford,107.0,2.0,Printer,3.0,Kessington Market
40,28,Darcee Byfford,120.0,1.0,Headphone,1.0,Brisby Mall
41,29,Roxane Lovell,NaN,NaN,NaN,NaN,NaN
42,30,Jacquette De Maine,101.0,5.0,Heater,2.0,Fairview Mall
43,30,Jacquette De Maine,111.0,4.0,Humidifier,2.0,Shoppers
44,30,Jacquette De Maine,114.0,15.0,Tripod,2.0,Rotunda
45,31,Claribel Lomen,NaN,NaN,NaN,NaN,NaN

In [13]:
products = pd.read_csv('/content/drive/MyDrive/udmy/dataAnalisys/Archivos/ABC - Products.csv')
products

    prod_id     product  price
0         1   Headphone     60
1         2     Printer    199
2         3     Speaker     95
3         4  Humidifier     70
4         5      Heater    150
5         6       Mouse     30
6         7    Keyboard     80
7         8    Bookcase    150
8         9      Vacuum    125
9        10     Blender     80
10       11         Rug    120
11       12         Fan    110
12       13  Microphone     85
13       14       Piano    250
14       15      Tripod     45
15       16       Mixer    185
16       17   Microwave    130
17       18      Washer    255
18       19       Dryer    280
19       20    Dumbbell     65
20       21  Hard drive     80

In [14]:
pd.merge(customers, sales, how = 'inner', on = 'cust_id')

,cust_id,customer,sale_id,prod_id,product,qty,store_location
0,2,Anthony Creech,116,3,Speaker,2,Brisby Mall
1,4,Femi Bello,109,5,Heater,2,Brisby Mall
2,4,Femi Bello,121,5,Heater,3,Shoppers
3,5,Michelle Rushworth,104,3,Speaker,3,Fairview Mall
4,5,Michelle Rushworth,119,5,Heater,2,Rotunda
5,7,Gaylor Jennins,126,2,Printer,2,Kessington Market
6,8,Kaia Raisher,110,3,Speaker,3,Shoppers
7,8,Kaia Raisher,112,13,Microphone,2,Kessington Market
8,8,Kaia Raisher,118,17,Microwave,3,Shoppers
9,10,Rozalie Roddie,105,4,Humidifier,1,Shoppers
10,10,Rozalie Roddie,117,3,Speaker,3,Kessington Market
11,10,Rozalie Roddie,123,1,Headphone,2,Kessington Market
12,13,Joycelin Karlik,113,5,Heater,2,Shoppers
13,13,Joycelin Karlik,124,15,Tripod,1,Brisby Mall
14,13,Joycelin Karlik,130,18,Washer,2,Shoppers
15,14,Celestia Gormally,106,4,Humidifier,1,Shoppers
16,14,Celestia Gormally,129,19,Dryer,1,Brisby Mall
17,15,Joline Bodsworth,128,13,Microphone,1,Rotunda
18,20,Fanchette Sinclar,102,14,Piano,2,Rotunda
19,20,Fanchette Sinclar,103,17,Microwave,1,Kessington Market
20,20,Fanchette Sinclar,115,13,Microphone,2,Kessington Market
21,24,Janka Taylorson,122,16,Mixer,2,Brisby Mall
22,24,Janka Taylorson,127,14,Piano,1,Kessington Market
23,27,Tafadzwa Warden,108,14,Piano,2,Brisby Mall
24,27,Tafadzwa Warden,125,17,Microwave,3,Shoppers
25,28,Darcee Byfford,107,2,Printer,3,Kessington Market
26,28,Darcee Byfford,120,1,Headphone,1,Brisby Mall
27,30,Jacquette De Maine,101,5,Heater,2,Fairview Mall
28,30,Jacquette De Maine,111,4,Humidifier,2,Shoppers
29,30,Jacquette De Maine,114,15,Tripod,2,Rotunda

In [15]:
customers.merge(sales, on = 'cust_id').head(2)

   cust_id        customer  sale_id  prod_id  product  qty store_location
0        2  Anthony Creech      116        3  Speaker    2    Brisby Mall
1        4      Femi Bello      109        5   Heater    2    Brisby Mall

In [16]:
customers.merge(sales, on = 'cust_id').merge(products, on = 'prod_id').head(2)

,cust_id,customer,sale_id,prod_id,product_x,qty,store_location,product_y,price
0,2,Anthony Creech,116,3,Speaker,2,Brisby Mall,Speaker,95
1,4,Femi Bello,109,5,Heater,2,Brisby Mall,Heater,150

In [17]:
customers.merge(sales, on = 'cust_id').merge(products[['prod_id', 'price']], on = 'prod_id').head(2)

,cust_id,customer,sale_id,prod_id,product,qty,store_location,price
0,2,Anthony Creech,116,3,Speaker,2,Brisby Mall,95
1,4,Femi Bello,109,5,Heater,2,Brisby Mall,150