In [1]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
fortune = pd.read_csv("/content/drive/MyDrive/udmy/dataAnalisys/Archivos/fortune1000.csv")
fortune = pd.read_csv("/content/drive/MyDrive/udmy/dataAnalisys/Archivos/fortune1000.csv", index_col = "Rank")
fortune

Mounted at /content/drive

,Company,Sector,Industry,Location,Revenues,Profits,Employees
Rank,,,,,,,
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",500343,9862,2300000
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",244363,19710,71200
3,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",242137,44940,377000
4,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",229234,48351,123000
5,UnitedHealth Group,Health Care,Health Care: Insurance and Managed Care,"Minnetonka, MN",201159,10558,260000
...,...,...,...,...,...,...,...
996,SiteOne Landscape Supply,Wholesalers,Wholesalers: Diversified,"Roswell, GA",1862,54,3664
997,Charles River Laboratories Intl,Health Care,Health Care: Pharmacy and Other Services,"Wilmington, MA",1858,123,11800
998,CoreLogic,Business Services,Financial Data Services,"Irvine, CA",1851,152,5900
999,Ensign Group,Health Care,Health Care: Medical Facilities,"Mission Viejo, CA",1849,40,21301
1000,HCP,Financials,Real estate,"Irvine, CA",1848,414,190

In [2]:
fortune.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 1 to 1000
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Company    1000 non-null   object
 1   Sector     1000 non-null   object
 2   Industry   1000 non-null   object
 3   Location   1000 non-null   object
 4   Revenues   1000 non-null   int64
 5   Profits    1000 non-null   int64
 6   Employees  1000 non-null   int64
dtypes: int64(3), object(4)
memory usage: 62.5+ KB

In [3]:
fortune.head(3)

,Company,Sector,Industry,Location,Revenues,Profits,Employees
Rank,,,,,,,
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",500343,9862,2300000
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",244363,19710,71200
3,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",242137,44940,377000

In [4]:
fortune.groupby('Sector')
x = fortune.groupby('Sector')
type(x)
x

In [5]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/udmy/dataAnalisys/Archivos/fortune1000.csv")
sector = df.groupby('Sector')
df.head(5)

,Rank,Company,Sector,Industry,Location,Revenues,Profits,Employees
0,1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",500343,9862,2300000
1,2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",244363,19710,71200
2,3,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",242137,44940,377000
3,4,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",229234,48351,123000
4,5,UnitedHealth Group,Health Care,Health Care: Insurance and Managed Care,"Minnetonka, MN",201159,10558,260000

In [6]:
sector

In [7]:
df["Sector"].unique()

array(['Retailing', 'Energy', 'Financials', 'Technology', 'Health Care',
       'Wholesalers', 'Telecommunications', 'Motor Vehicles &  Parts',
       'Food &  Drug Stores', 'Industrials', 'Aerospace &  Defense',
       'Household Products', 'Transportation',
       'Food, Beverages &  Tobacco', 'Chemicals', 'Media', 'Apparel',
       'Materials', 'Hotels, Restaurants &  Leisure', 'Business Services',
       'Engineering &  Construction'], dtype=object)

In [8]:
sector.size()

Sector
Aerospace &  Defense               25
Apparel                            14
Business Services                  53
Chemicals                          33
Energy                            107
Engineering &  Construction        27
Financials                        155
Food &  Drug Stores                12
Food, Beverages &  Tobacco         37
Health Care                        71
Hotels, Restaurants &  Leisure     26
Household Products                 28
Industrials                        49
Materials                          45
Media                              25
Motor Vehicles &  Parts            19
Retailing                          77
Technology                        103
Telecommunications                 10
Transportation                     40
Wholesalers                        44
dtype: int64

In [9]:
df["Sector"].value_counts()

Sector
Financials                        155
Energy                            107
Technology                        103
Retailing                          77
Health Care                        71
Business Services                  53
Industrials                        49
Materials                          45
Wholesalers                        44
Transportation                     40
Food, Beverages &  Tobacco         37
Chemicals                          33
Household Products                 28
Engineering &  Construction        27
Hotels, Restaurants &  Leisure     26
Media                              25
Aerospace &  Defense               25
Motor Vehicles &  Parts            19
Apparel                            14
Food &  Drug Stores                12
Telecommunications                 10
Name: count, dtype: int64

In [10]:
sector.first()

,Rank,Company,Industry,Location,Revenues,Profits,Employees
Sector,,,,,,,
Aerospace & Defense,27,Boeing,Aerospace and Defense,"Chicago, IL",93392,8197,140800
Apparel,89,Nike,Apparel,"Beaverton, OR",34350,4240,74400
Business Services,143,ManpowerGroup,Temporary Help,"Milwaukee, WI",21034,545,29000
Chemicals,47,DowDuPont,Chemicals,"Midland, Michigan",62683,1460,98000
Energy,2,Exxon Mobil,Petroleum Refining,"Irving, TX",244363,19710,71200
Engineering & Construction,153,Fluor,"Engineering, Construction","Irving, TX",19521,191,56706
Financials,3,Berkshire Hathaway,Insurance: Property and Casualty (Stock),"Omaha, NE",242137,44940,377000
Food & Drug Stores,17,Kroger,Food and Drug Stores,"Cincinnati, OH",122662,1907,449000
"Food, Beverages & Tobacco",45,PepsiCo,Food Consumer Products,"Harrison, NY",63525,4857,263000
Health Care,5,UnitedHealth Group,Health Care: Insurance and Managed Care,"Minnetonka, MN",201159,10558,260000
"Hotels, Restaurants & Leisure",127,Marriott International,"Hotels, Casinos, Resorts","Bethesda, MD",22894,1372,177000
Household Products,42,Procter & Gamble,Household and Personal Products,"Cincinnati, OH",66217,15326,95000
Industrials,18,General Electric,Industrial Machinery,"Boston, MA",122274,-5786,313000
Materials,124,International Paper,"Packaging, Containers","Memphis, TN",23302,2144,56000
Media,55,Disney,Entertainment,"Burbank, CA",55137,8980,199000
Motor Vehicles & Parts,10,General Motors,Motor Vehicles and Parts,"Detroit, MI",157311,-3864,180000
Retailing,1,Walmart,General Merchandisers,"Bentonville, AR",500343,9862,2300000
Technology,4,Apple,"Computers, Office Equipment","Cupertino, CA",229234,48351,123000
Telecommunications,9,AT&T,Telecommunications,"Dallas, TX",160546,29450,254000
Transportation,44,UPS,"Mail, Package, and Freight Delivery","Atlanta, GA",65872,4910,346415
Wholesalers,6,McKesson,Wholesalers: Health Care,"SF, CA",198533,5070,64500

In [11]:
sector.last()

,Rank,Company,Industry,Location,Revenues,Profits,Employees
Sector,,,,,,,
Aerospace & Defense,989,Aerojet Rocketdyne Holdings,Aerospace and Defense,"El Segundo, CA",1877,-10,5157
Apparel,862,Wolverine World Wide,Apparel,"Rockford, MI",2350,0,3700
Business Services,998,CoreLogic,Financial Data Services,"Irvine, CA",1851,152,5900
Chemicals,979,Stepan,Chemicals,"Northfield, IL",1925,91,2096
Energy,991,Superior Energy Services,"Oil and Gas Equipment, Services","Houston, TX",1874,-206,6400
Engineering & Construction,987,TopBuild,"Engineering, Construction","Daytona Beach, FL",1906,158,8400
Financials,1000,HCP,Real estate,"Irvine, CA",1848,414,190
Food & Drug Stores,942,Freds,Food and Drug Stores,"Memphis, TN",2064,-141,7324
"Food, Beverages & Tobacco",938,Universal,Tobacco,"Richmond, VA",2071,106,24000
Health Care,999,Ensign Group,Health Care: Medical Facilities,"Mission Viejo, CA",1849,40,21301
"Hotels, Restaurants & Leisure",985,Vail Resorts,"Hotels, Casinos, Resorts","Broomfield, CO",1907,210,20150
Household Products,968,ACCO Brands,"Home Equipment, Furnishings","Lake Zurich, IL",1949,131,6620
Industrials,982,Rexnord,Industrial Machinery,"Milwaukee, WI",1918,74,8000
Materials,975,Summit Materials,"Building Materials, Glass","Denver, CO",1933,121,6000
Media,994,Tribune Media,Entertainment,"Chicago, IL",1867,194,6000
Motor Vehicles & Parts,941,Tower International,Motor Vehicles and Parts,"Livonia, MI",2066,47,7600
Retailing,993,Childrens Place,Specialty Retailers: Apparel,"Secaucus, NJ",1870,84,9800
Technology,992,VeriFone Systems,Financial Data Services,"San Jose, CA",1871,-174,5600
Telecommunications,908,Zayo Group Holdings,Telecommunications,"Boulder, CO",2200,85,3794
Transportation,969,Echo Global Logistics,Transportation and Logistics,"Chicago, IL",1943,12,2453
Wholesalers,996,SiteOne Landscape Supply,Wholesalers: Diversified,"Roswell, GA",1862,54,3664

In [12]:
sector.get_group("Retailing")
sector.get_group("Health Care")
#sector.get_group("Energy")

,Rank,Company,Sector,Industry,Location,Revenues,Profits,Employees
4,5,UnitedHealth Group,Health Care,Health Care: Insurance and Managed Care,"Minnetonka, MN",201159,10558,260000
6,7,CVS Health,Health Care,Health Care: Pharmacy and Other Services,"Woonsocket, RI",184765,6622,203000
24,25,Express Scripts Holding,Health Care,Health Care: Pharmacy and Other Services,"St. Louis, MO",100065,4517,26600
28,29,Anthem,Health Care,Health Care: Insurance and Managed Care,"Indianapolis, IN",90040,3842,56000
36,37,Johnson & Johnson,Health Care,Pharmaceuticals,"New Brunswick, NJ",76450,1300,134000
...,...,...,...,...,...,...,...,...
956,957,AMN Healthcare Services,Health Care,Health Care: Pharmacy and Other Services,"San Diego, CA",1989,132,2980
960,961,IDEXX Laboratories,Health Care,Medical Products and Equipment,"Westbrook, ME",1969,263,7600
994,995,Healthcare Services Group,Health Care,Health Care: Pharmacy and Other Services,"Bensalem, PA",1866,88,55000
996,997,Charles River Laboratories Intl,Health Care,Health Care: Pharmacy and Other Services,"Wilmington, MA",1858,123,11800
998,999,Ensign Group,Health Care,Health Care: Medical Facilities,"Mission Viejo, CA",1849,40,21301

In [13]:
df["Sector"] == "Energy"
mask = df["Sector"] == "Energy"
df[mask]

,Rank,Company,Sector,Industry,Location,Revenues,Profits,Employees
1,2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",244363,19710,71200
12,13,Chevron,Energy,Petroleum Refining,"San Ramon, CA",134533,9195,51900
27,28,Phillips 66,Energy,Petroleum Refining,"Houston, TX",91568,5106,14600
30,31,Valero Energy,Energy,Petroleum Refining,"San Antonio, TX",88407,4065,10015
40,41,Marathon Petroleum,Energy,Petroleum Refining,"Findlay, OH",67610,3432,43800
...,...,...,...,...,...,...,...,...
953,954,California Resources,Energy,"Mining, Crude-Oil Production","Los Angeles, CA",2006,-266,1450
976,977,Ferrellgas Partners,Energy,Energy,"Overland Park, KS",1930,-55,3891
979,980,Oceaneering International,Energy,"Oil and Gas Equipment, Services","Houston, TX",1922,166,8200
980,981,Cimarex Energy,Energy,"Mining, Crude-Oil Production","Denver, CO",1918,494,910
990,991,Superior Energy Services,Energy,"Oil and Gas Equipment, Services","Houston, TX",1874,-206,6400

In [14]:
#df.set_index("Rank", inplace = True)
df

,Rank,Company,Sector,Industry,Location,Revenues,Profits,Employees
0,1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",500343,9862,2300000
1,2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",244363,19710,71200
2,3,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",242137,44940,377000
3,4,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",229234,48351,123000
4,5,UnitedHealth Group,Health Care,Health Care: Insurance and Managed Care,"Minnetonka, MN",201159,10558,260000
...,...,...,...,...,...,...,...,...
995,996,SiteOne Landscape Supply,Wholesalers,Wholesalers: Diversified,"Roswell, GA",1862,54,3664
996,997,Charles River Laboratories Intl,Health Care,Health Care: Pharmacy and Other Services,"Wilmington, MA",1858,123,11800
997,998,CoreLogic,Business Services,Financial Data Services,"Irvine, CA",1851,152,5900
998,999,Ensign Group,Health Care,Health Care: Medical Facilities,"Mission Viejo, CA",1849,40,21301
999,1000,HCP,Financials,Real estate,"Irvine, CA",1848,414,190

In [15]:
sector.sum()
sector["Employees"].sum()
sector["Employees"].mean()

Sector
Aerospace &  Defense               40404.960000
Apparel                            25407.071429
Business Services                  30075.452830
Chemicals                          14364.242424
Energy                              9170.158879
Engineering &  Construction        15583.148148
Financials                         22581.412903
Food &  Drug Stores               116506.166667
Food, Beverages &  Tobacco         29170.702703
Health Care                        41847.732394
Hotels, Restaurants &  Leisure     88628.346154
Household Products                 24103.428571
Industrials                        31961.428571
Materials                          14527.800000
Media                              21839.400000
Motor Vehicles &  Parts            49662.210526
Retailing                          88320.233766
Technology                         31036.961165
Telecommunications                 78560.900000
Transportation                     41302.825000
Wholesalers                        16913.068182
Name: Employees, dtype: float64

In [16]:
sector.agg({"Revenues" : "mean", "Profits" : "mean", "Employees" : "sum"})
sector.agg({"Revenues" : ["mean", "max"], "Profits" : "mean", "Employees" : "sum"})
sector.agg({"Revenues" : ["mean", "max"], "Profits" : ["max", "min"], "Employees" : "sum"})

                                    Revenues         Profits       Employees
                                        mean     max     max   min       sum
Sector
Aerospace &  Defense            15353.400000   93392    8197   -74   1010124
Apparel                          7225.500000   34350    4240  -479    355699
Business Services                5963.962264   21034    6699  -558   1593999
Chemicals                        7610.636364   62683    3000  -297    474020
Energy                          14425.299065  244363   19710 -5723    981207
Engineering &  Construction      6399.333333   19521    1038  -333    420745
Financials                      15757.935484  242137   44940 -6798   3500119
Food &  Drug Stores             33789.000000  122662    4078  -374   1398074
Food, Beverages &  Tobacco      13790.054054   63525   10999  -287   1079316
Health Care                     21239.309859  201159   21308 -2459   2971189
Hotels, Restaurants &  Leisure   6916.346154   22894    5192  -375   2304337
Household Products               8277.821429   66217   15326 -1054    674896
Industrials                     10615.102041  122274    4858 -5786   1566110
Materials                        6184.400000   23302    2144  -258    653751
Media                            9219.480000   55137    8980  -738    545985
Motor Vehicles &  Parts         22817.631579  157311    7602 -3864    943582
Retailing                       21874.714286  500343    9862 -1068   6800658
Technology                      13347.786408  229234   48351 -3728   3196807
Telecommunications              46695.900000  160546   30101 -2117    785609
Transportation                  11379.000000   65872   10712  -107   1652113
Wholesalers                     20185.204545  198533    5070  -267    744175

In [17]:
fortune = df
fortune
sectors = fortune.groupby('Sector')
fortune

,Rank,Company,Sector,Industry,Location,Revenues,Profits,Employees
0,1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",500343,9862,2300000
1,2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",244363,19710,71200
2,3,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",242137,44940,377000
3,4,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",229234,48351,123000
4,5,UnitedHealth Group,Health Care,Health Care: Insurance and Managed Care,"Minnetonka, MN",201159,10558,260000
...,...,...,...,...,...,...,...,...
995,996,SiteOne Landscape Supply,Wholesalers,Wholesalers: Diversified,"Roswell, GA",1862,54,3664
996,997,Charles River Laboratories Intl,Health Care,Health Care: Pharmacy and Other Services,"Wilmington, MA",1858,123,11800
997,998,CoreLogic,Business Services,Financial Data Services,"Irvine, CA",1851,152,5900
998,999,Ensign Group,Health Care,Health Care: Medical Facilities,"Mission Viejo, CA",1849,40,21301
999,1000,HCP,Financials,Real estate,"Irvine, CA",1848,414,190

In [18]:
sector.size()

Sector
Aerospace &  Defense               25
Apparel                            14
Business Services                  53
Chemicals                          33
Energy                            107
Engineering &  Construction        27
Financials                        155
Food &  Drug Stores                12
Food, Beverages &  Tobacco         37
Health Care                        71
Hotels, Restaurants &  Leisure     26
Household Products                 28
Industrials                        49
Materials                          45
Media                              25
Motor Vehicles &  Parts            19
Retailing                          77
Technology                        103
Telecommunications                 10
Transportation                     40
Wholesalers                        44
dtype: int64

In [19]:
df = pd.DataFrame(columns = fortune.columns)
df

Empty DataFrame
Columns: [Rank, Company, Sector, Industry, Location, Revenues, Profits, Employees]
Index: []