In [1]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
nba = pd.read_excel("/content/drive/MyDrive/udmy/dataAnalisys/Archivos/NbaTeams.xlsx")
nba.head()

Mounted at /content/drive

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH

In [2]:
nba["Teams"] = " "
nba["nba Teams"] = " "
nba.head()

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country,Teams,nba Teams
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS,,
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US,,
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO,,
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US,,
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH,,

In [3]:
#nba.Name
#nba.nba Teams
nba.Teams
#nba.Sports

0
1
2
3
4
      ..
493
494
495
496
497
Name: Teams, Length: 498, dtype: object

In [4]:
nba["Sports"] = "basket"
nba.head()

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country,Teams,nba Teams,Sports
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS,,,basket
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US,,,basket
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO,,,basket
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US,,,basket
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH,,,basket

In [5]:
nba.drop("Teams", axis = 1, inplace = True)
#nba.insert(2, column = "Teams", value = "Colombians")
#nba.insert(2, column = "Sportss", value = "Turmequé")
nba

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country,nba Teams,Sports
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS,,basket
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US,,basket
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO,,basket
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US,,basket
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH,,basket
...,...,...,...,...,...,...,...,...,...,...,...,...
493,Rui Hachimura,Washington Wizards,SouthEast,F,6'8,230.0,1998-02-08,Gonzaga,4692840.0,JP,,basket
494,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,,basket
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12,UCLA,41358814.0,US,,basket
496,Thomas Bryant,Washington Wizards,SouthEast,C,6'10,248.0,1997-07-31,Indiana,8333333.0,US,,basket
497,Troy Brown Jr.,Washington Wizards,SouthEast,G-F,6'6,215.0,1999-07-28,Oregon,3372840.0,US,,basket

In [6]:
nba

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country,nba Teams,Sports
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS,,basket
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US,,basket
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO,,basket
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US,,basket
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH,,basket
...,...,...,...,...,...,...,...,...,...,...,...,...
493,Rui Hachimura,Washington Wizards,SouthEast,F,6'8,230.0,1998-02-08,Gonzaga,4692840.0,JP,,basket
494,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,,basket
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12,UCLA,41358814.0,US,,basket
496,Thomas Bryant,Washington Wizards,SouthEast,C,6'10,248.0,1997-07-31,Indiana,8333333.0,US,,basket
497,Troy Brown Jr.,Washington Wizards,SouthEast,G-F,6'6,215.0,1999-07-28,Oregon,3372840.0,US,,basket

In [7]:
nba.insert(2, column = "Teams", value = "Colombians")

In [8]:
nba

,Name,Team,Teams,Division,Position,Height,Weight,Birth_Date,College,Salary,Country,nba Teams,Sports
0,Bogdan Bogdanovic,Atlanta Hawks,Colombians,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS,,basket
1,Brandon Goodwin,Atlanta Hawks,Colombians,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US,,basket
2,Bruno Fernando,Atlanta Hawks,Colombians,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO,,basket
3,Cam Reddish,Atlanta Hawks,Colombians,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US,,basket
4,Clint Capela,Atlanta Hawks,Colombians,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH,,basket
...,...,...,...,...,...,...,...,...,...,...,...,...,...
493,Rui Hachimura,Washington Wizards,Colombians,SouthEast,F,6'8,230.0,1998-02-08,Gonzaga,4692840.0,JP,,basket
494,NaN,NaN,Colombians,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,,basket
495,Russell Westbrook,Washington Wizards,Colombians,SouthEast,G,6'3,200.0,1988-11-12,UCLA,41358814.0,US,,basket
496,Thomas Bryant,Washington Wizards,Colombians,SouthEast,C,6'10,248.0,1997-07-31,Indiana,8333333.0,US,,basket
497,Troy Brown Jr.,Washington Wizards,Colombians,SouthEast,G-F,6'6,215.0,1999-07-28,Oregon,3372840.0,US,,basket