In [1]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
emp = pd.read_csv("/content/drive/MyDrive/udmy/dataAnalisys/Archivos/Employee.csv")
emp.head()

Mounted at /content/drive

                    name   department          position       salary
0     JEDIDIAH, PALLAS O      FINANCE  PYTHON DEVELOPER  $108,156.28
1  FLORETTE, JODLOWSKI R    MARKETING          DIRECTOR   $85,000.00
2       KIZZIE, PAULUS D  PROCUREMENT          DIRECTOR   $85,000.00
3      ENNIS, MACQUIST N        SALES      DATA ANALYST   $76,715.61
4       VAIL, HONATSCH R       DESIGN         DEVELOPER  $117,247.37

In [2]:
emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1010 entries, 0 to 1009
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        1010 non-null   object
 1   department  1010 non-null   object
 2   position    1010 non-null   object
 3   salary      1010 non-null   object
dtypes: object(4)
memory usage: 31.7+ KB

In [3]:
emp.nunique()

name          1010
department      11
position        26
salary         947
dtype: int64

In [4]:
emp[["department", "position"]] = emp[["department", "position"]].astype("category")

In [5]:
emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1010 entries, 0 to 1009
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        1010 non-null   object
 1   department  1010 non-null   category
 2   position    1010 non-null   category
 3   salary      1010 non-null   object
dtypes: category(2), object(2)
memory usage: 19.5+ KB

In [6]:
"happy".upper()
"PYTHON".lower()

'python'

In [8]:
emp["name"]
emp["name"].str.lower().str.title()

0          Jedidiah, Pallas O
1       Florette, Jodlowski R
2            Kizzie, Paulus D
3           Ennis, Macquist N
4            Vail, Honatsch R
                ...
1005           James, Bolam M
1006       Carlynn, Eddolls A
1007        Rozelle, Foston S
1008           Alard, Ekins J
1009           Aloin, Reade C
Name: name, Length: 1010, dtype: object