In [1]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
nba = pd.read_excel('/content/drive/MyDrive/udmy/dataAnalisys/Archivos/NbaTeams.xlsx')

Mounted at /content/drive

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
nba["Salary"]

0      18000000.0
1       1701593.0
2       1517981.0
3             NaN
4      16000000.0
          ...
493     4692840.0
494           NaN
495    41358814.0
496     8333333.0
497     3372840.0
Name: Salary, Length: 498, dtype: float64

In [4]:
nba["Salary"].add(50000)

0      18050000.0
1       1751593.0
2       1567981.0
3             NaN
4      16050000.0
          ...
493     4742840.0
494           NaN
495    41408814.0
496     8383333.0
497     3422840.0
Name: Salary, Length: 498, dtype: float64

In [5]:
nba["Salary"] + 2000000

0      20000000.0
1       3701593.0
2       3517981.0
3             NaN
4      18000000.0
          ...
493     6692840.0
494           NaN
495    43358814.0
496    10333333.0
497     5372840.0
Name: Salary, Length: 498, dtype: float64

In [6]:
nba["bonus_salary"] = nba["Salary"] + 30000
nba

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country,bonus_salary
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS,18030000.0
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US,1731593.0
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO,1547981.0
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US,NaN
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH,16030000.0
...,...,...,...,...,...,...,...,...,...,...,...
493,Rui Hachimura,Washington Wizards,SouthEast,F,6'8,230.0,1998-02-08,Gonzaga,4692840.0,JP,4722840.0
494,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12,UCLA,41358814.0,US,41388814.0
496,Thomas Bryant,Washington Wizards,SouthEast,C,6'10,248.0,1997-07-31,Indiana,8333333.0,US,8363333.0
497,Troy Brown Jr.,Washington Wizards,SouthEast,G-F,6'6,215.0,1999-07-28,Oregon,3372840.0,US,3402840.0

In [7]:
nba["Salary"].sub(55000)
#nba["Salary"] - sub(55000)

0      17945000.0
1       1646593.0
2       1462981.0
3             NaN
4      15945000.0
          ...
493     4637840.0
494           NaN
495    41303814.0
496     8278333.0
497     3317840.0
Name: Salary, Length: 498, dtype: float64

In [8]:
nba["Salary"].div(1000000)
#nba["Salary"]/1000000

0      18.000000
1       1.701593
2       1.517981
3            NaN
4      16.000000
         ...
493     4.692840
494          NaN
495    41.358814
496     8.333333
497     3.372840
Name: Salary, Length: 498, dtype: float64

In [9]:
nba["Weight"].mul(0.453592)
#nba["Weight"]*0.453592

0       99.790240
1       81.646560
2      108.862080
3       98.883056
4      108.862080
          ...
493    104.326160
494           NaN
495     90.718400
496    112.490816
497     97.522280
Name: Weight, Length: 498, dtype: float64