In [1]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
courses = pd.read_csv('/content/drive/MyDrive/udmy/dataAnalisys/Archivos/COLLEGE - Courses.csv')
grades = pd.read_csv('/content/drive/MyDrive/udmy/dataAnalisys/Archivos/COLLEGE - Grades.csv')
students = pd.read_csv('/content/drive/MyDrive/udmy/dataAnalisys/Archivos/COLLEGE - Students.csv')

Mounted at /content/drive

In [2]:
courses

  course_id              course_name semester
0    BIO101  introduction to biology     fall
1    CSC098       data visualization   summer
2    CSC220            data analysis   spring
3    DBA305  database administration   spring
4    ECN322    cost benefit analysis   summer
5    ECN433            globalization     fall
6    MTH230                  vectors     fall

In [3]:
grades.head()

   grade  student_id course_id
0     85        2323    CSC098
1     90        2323    DBA305
2     90        2329    CSC098
3     90        2329    DBA305
4     95        2329    ECN322

In [4]:
students.head()

   student_id first_name last_name  gender
0        2323         tj     adams    male
1        2326  christine     adams     NaN
2        2329       paul   fischer    male
3        2332       abby    badmus  female
4        2335      maria     jones     NaN

In [5]:
pd.merge(students, grades, on = 'student_id').head()

   student_id first_name last_name gender  grade course_id
0        2323         tj     adams   male     85    CSC098
1        2323         tj     adams   male     90    DBA305
2        2329       paul   fischer   male     90    CSC098
3        2329       paul   fischer   male     90    DBA305
4        2329       paul   fischer   male     95    ECN322

In [6]:
df = pd.merge(students, grades, on = 'student_id').sort_values('grade', ascending = False).head(10)
df.head()

    student_id first_name last_name  gender  grade course_id
19        2359     joanne     price  female    100    ECN433
25        2368    melinda     smart  female     98    ECN322
23        2368    melinda     smart  female     98    CSC220
9         2338    johnson     banky    male     98    CSC098
21        2365         rj      lara    male     96    CSC098

In [7]:
df['student_id'] == 2332
df[df['student_id'] == 2332]

   student_id first_name last_name  gender  grade course_id
7        2332       abby    badmus  female     94    MTH230
6        2332       abby    badmus  female     93    DBA305

In [8]:
df[df['student_id'] == 2368]

    student_id first_name last_name  gender  grade course_id
25        2368    melinda     smart  female     98    ECN322
23        2368    melinda     smart  female     98    CSC220

In [9]:
students_rec = students.merge(grades, on = 'student_id')
students_rec.head()

   student_id first_name last_name gender  grade course_id
0        2323         tj     adams   male     85    CSC098
1        2323         tj     adams   male     90    DBA305
2        2329       paul   fischer   male     90    CSC098
3        2329       paul   fischer   male     90    DBA305
4        2329       paul   fischer   male     95    ECN322

In [10]:
students_rec1 = students_rec.merge(courses, on = 'course_id')
students_rec1.head()

,student_id,first_name,last_name,gender,grade,course_id,course_name,semester
0,2323,tj,adams,male,85,CSC098,data visualization,summer
1,2323,tj,adams,male,90,DBA305,database administration,spring
2,2329,paul,fischer,male,90,CSC098,data visualization,summer
3,2329,paul,fischer,male,90,DBA305,database administration,spring
4,2329,paul,fischer,male,95,ECN322,cost benefit analysis,summer

In [11]:
reg_course = students_rec1.groupby('course_name')
reg_course.size().sort_values()

course_name
introduction to biology    2
data analysis              3
cost benefit analysis      4
globalization              6
data visualization         7
database administration    8
vectors                    8
dtype: int64

In [12]:
students_records = students_rec1.groupby(['course_name', 'last_name', 'first_name', 'grade'])

In [13]:
students_records.size()

course_name              last_name  first_name  grade
cost benefit analysis    andrew     melissa     90       1
                         banky      johnson     90       1
                         fischer    paul        95       1
                         smart      melinda     98       1
data analysis            banky      johnson     90       1
                         lara       rj          90       1
                         smart      melinda     98       1
data visualization       abubarka   fatima      85       1
                         adams      tj          85       1
                         banky      johnson     98       1
                         ceasar     romeo       80       1
                         fischer    paul        90       1
                         lara       rj          96       1
                         sylvester  tobias      90       1
database administration  abubarka   fatima      90       1
                         adams      tj          90       1
                         badmus     abby        93       1
                         fischer    paul        90       1
                         jones      maria       80       1
                         patterson  kevin       90       1
                         singh      pooja       87       1
                         smart      melinda     90       1
globalization            abubarka   fatima      95       1
                         anderson   abigael     80       1
                         brent      max         87       1
                         price      joanne      100      1
                         schmidts   paula       87       1
                         smart      melinda     90       1
introduction to biology  andrew     melissa     92       1
                         cooper     alice       95       1
vectors                  abubarka   fatima      90       1
                         anderson   abigael     82       1
                         badmus     abby        94       1
                         banky      johnson     85       1
                         drogba     george      87       1
                         fischer    paul        92       1
                         jones      christine   90       1
                         sylvester  tobias      80       1
dtype: int64

In [14]:
students_rec1.head()

,student_id,first_name,last_name,gender,grade,course_id,course_name,semester
0,2323,tj,adams,male,85,CSC098,data visualization,summer
1,2323,tj,adams,male,90,DBA305,database administration,spring
2,2329,paul,fischer,male,90,CSC098,data visualization,summer
3,2329,paul,fischer,male,90,DBA305,database administration,spring
4,2329,paul,fischer,male,95,ECN322,cost benefit analysis,summer

In [15]:
grades.head()
#pd.merge(students_rec1, grades, left = 'id', right_on = 'student_id')

   grade  student_id course_id
0     85        2323    CSC098
1     90        2323    DBA305
2     90        2329    CSC098
3     90        2329    DBA305
4     95        2329    ECN322